name: homeconnect
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_analytics: ^11.5.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  cloud_functions: 5.5.2
  google_sign_in: ^5.4.4
  image_picker: ^1.1.0
  firebase_storage: ^12.0.0
  geolocator: ^14.0.1
  geocoding: ^3.0.0
  table_calendar: ^3.0.9
  intl: ^0.19.0
  permission_handler: ^12.0.0+1
  firebase_messaging: ^15.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # recommended lints

# The following section is specific to Flutter packages.
flutter:
  # Include the Material Icons font.
  uses-material-design: true

  # App assets
  assets:
    - lib/assets/google_logo.png
    - lib/assets/images/babysitting.png
    - lib/assets/images/compound_cleaning.jpg
    - lib/assets/images/compound_cleaning2.jpg
    - lib/assets/images/compound_cleaning3.jpg
    - lib/assets/images/cooking.jpg
    - lib/assets/images/laundry.png
    - lib/assets/images/painting.png
    - lib/assets/images/painting2.png
    - lib/assets/images/roof_cleaning.png
    - lib/assets/images/house_cleaning.jpg
    - lib/assets/images/gardening.jpg
    - lib/assets/images/gardening2.jpg
    - lib/assets/images/furn_moving.png
    - lib/assets/images/furn_repair.png
  #   - images/a_dot_ham.jpeg

  # ---- fonts examples kept for reference ----
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
