// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfUWwr3W2J_pJy4tDtn47A7kT0JbUPnw',
    appId: '1:279318295980:web:6e81cfbc35297a783e7609',
    messagingSenderId: '279318295980',
    projectId: 'homeconnect-a9d5c',
    authDomain: 'homeconnect-a9d5c.firebaseapp.com',
    storageBucket: 'homeconnect-a9d5c.firebasestorage.app',
    measurementId: 'G-EDCY4369RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHtXul2nzX9Xe2xLr_wLpe0-K4XS3E1Y',
    appId: '1:279318295980:android:4fcf9376f7b3a33a3e7609',
    messagingSenderId: '279318295980',
    projectId: 'homeconnect-a9d5c',
    storageBucket: 'homeconnect-a9d5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx8q--8hNIcCR82ol1s9AtuYGDY_w1roo',
    appId: '1:279318295980:ios:d859df32ed3b04653e7609',
    messagingSenderId: '279318295980',
    projectId: 'homeconnect-a9d5c',
    storageBucket: 'homeconnect-a9d5c.firebasestorage.app',
    iosBundleId: 'com.example.homeconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx8q--8hNIcCR82ol1s9AtuYGDY_w1roo',
    appId: '1:279318295980:ios:d859df32ed3b04653e7609',
    messagingSenderId: '279318295980',
    projectId: 'homeconnect-a9d5c',
    storageBucket: 'homeconnect-a9d5c.firebasestorage.app',
    iosBundleId: 'com.example.homeconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmfUWwr3W2J_pJy4tDtn47A7kT0JbUPnw',
    appId: '1:279318295980:web:155c474592de53d53e7609',
    messagingSenderId: '279318295980',
    projectId: 'homeconnect-a9d5c',
    authDomain: 'homeconnect-a9d5c.firebaseapp.com',
    storageBucket: 'homeconnect-a9d5c.firebasestorage.app',
    measurementId: 'G-9QYFS5LK99',
  );
}
